apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
  namespace: heart-disease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: api
          image: heart-disease-mlops:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /app/models/model.joblib
            - name: MODEL_METADATA_PATH
              value: /app/models/metadata.json
            - name: MLFLOW_TRACKING_URI
              value: file:/app/mlruns
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30

