apiVersion: v1
kind: Service
metadata:
  name: heart-ui
  namespace: heart-disease
spec:
  selector:
    app: heart-ui
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  type: LoadBalancer

