{
 "title": "Heart Disease API",
 "refresh": "10s",
 "panels": [
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(heart_api_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Prediction Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(heart_prediction_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Predictions By Class",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(heart_predictions_total) by (prediction)",
     "legendFormat": "class {{prediction}}"
    }
   ]
  }
 ]
}